'use client'
import NavBar from "./components/NavBar";
import "./globals.css";
import Providers from "@/redux/provider";
import { alata } from "./fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${alata.className}  h-screen  `}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
