import NavBar from "./components/NavBar";
import "./globals.css";
import Providers from "@/redux/provider";
import { alata, josefinSans } from "../public/fonts/fonts";
import Footer from "./components/Footer";

export const metadata = {
  title: "Loop Studios",
  description: "Generated by create next app",
};

async function RootLayout({ children }) {
  return (
    <html lang="en" className={`${alata.variable} ${josefinSans.variable}`}>
      <body suppressHydrationWarning={true} className={` h-screen font-alata `}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
export default RootLayout;
