"use client";
import NavBar from "./components/NavBar";
import "./globals.css";
import Providers from "@/redux/provider";
import { alata } from "../public/fonts/fonts";
import Footer from "./components/Footer";
import getPhotos from "./lib/getPhotos";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  // const headerImages = await getPhotos('virtual reality',3)
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${alata.className} h-screen  `}>
        <Providers>
          <NavBar  />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
